# Generated by Django 3.2.5 on 2021-08-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created'], 'verbose_name': 'servicio', 'verbose_name_plural': 'servicios'},
        ),
        migrations.AddField(
            model_name='service',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='Fecha de edición'),
        ),
    ]
